name: Test

on:
  push:

jobs:
  pytest:
    runs-on: ubuntu-latest

    env:
      USE_LOCAL_DDB: "true"
      AWS_DEFAULT_REGION: "us-west-2"
      AWS_ACCESS_KEY_ID: "***"
      AWS_SECRET_ACCESS_KEY: "***"
      LOCAL_DDB_ENDPOINT_URL: "http://localhost:8000"

    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9, "3.10"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python-dev
          pip install boto3
          pip install tenacity
          pip install sqlalchemy
      - name: black
        run: |
          pip install black
          black --check pydynamodb
      - name: flake8
        run: |
          pip install flake8
          flake8 --max-line-length=120 pydynamodb
      - name: Download DynamoDB local
        run: |
          curl -O https://s3.us-west-2.amazonaws.com/dynamodb-local/dynamodb_local_latest.tar.gz
          tar xzf ./dynamodb_local_latest.tar.gz
          nohup java -Djava.library.path=./DynamoDBLocal_lib -jar DynamoDBLocal.jar -sharedDb &
      - name: Run test with pytest
        run: |
          pip install pytest
          pip install pytest-cov
          pytest --cov=pydynamodb --cov-report=xml tests/
      - name: Upload test coverage
        uses: codecov/codecov-action@v3
        with:
          env_vars: OS,PYTHON
          files: ./coverage.xml
          flags: unittests
          fail_ci_if_error: true
          verbose: true
